# PostgreSQL runtime configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
server.port=${PORT:8181}
server.error.whitelabel.enabled=false
